export enum ECurrency {
  BGN = "BGN",
  NZD = "NZD",
  ILS = "ILS",
  RUB = "RUB",
  CAD = "CAD",
  USD = "USD",
  PHP = "PHP",
  CHF = "CHF",
  AUD = "AUD",
  JPY = "JPY",
  TRY = "TRY",
  HKD = "HKD",
  MYR = "MYR",
  HRK = "HRK",
  CZK = "CZK",
  IDR = "IDR",
  DKK = "DKK",
  NOK = "NOK",
  HUF = "HUF",
  GBP = "GBP",
  MXN = "MXN",
  THB = "THB",
  ISK = "ISK",
  ZAR = "ZAR",
  BRL = "BRL",
  SGD = "SGD",
  PLN = "PLN",
  INR = "INR",
  KRW = "KRW",
  RON = "RON",
  CNY = "CNY",
  SEK = "SEK",
  EUR = "EUR"
}

export const { AUD, BGN, BRL, CAD, CHF, CNY, CZK, DKK, EUR, GBP, HKD, HRK, HUF, IDR, ILS, INR, ISK, JPY, KRW, MXN, MYR, NOK, NZD, PHP, PLN, RON, RUB, SEK, SGD, THB, TRY, USD, ZAR } = ECurrency